# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 501e9ed3dd0599c542c0c099b3aa09c5b0e585404fc2ac1dcd41b0a3840e89064766a66f861bbf936b4f7c3e773b63c3e4cd3807699eac08f75c3c8a4c5f3358

test:
  secret_key_base: 49139a8efd29ce74b136654e2bcf28a4d8aad2fd85b835e322bd87e0fd2ce91eaa09f7b3c0c98094f26d90e1196714c2620afbaa11db1b204fe3b60228cc6842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
